# Generated by Django 3.0 on 2019-12-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('north', models.CharField(max_length=200)),
                ('south', models.CharField(max_length=200)),
                ('east', models.CharField(max_length=200)),
                ('west', models.CharField(max_length=200)),
            ],
        ),
    ]
