# Generated by Django 3.0 on 2019-12-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simage',
            name='upload',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
