# Generated by Django 2.1.7 on 2019-12-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20191203_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simage',
            name='model',
            field=models.CharField(choices=[('1', 'Red Neuronal 1'), ('2', 'Red Neuronal 2'), ('3', 'Naive Bayes 1'), ('4', 'Naive Bayes 2')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='simage',
            name='status',
            field=models.CharField(choices=[('0', 'Waiting'), ('1', 'Processing'), ('2', 'Processed'), ('3', 'Error')], max_length=2),
        ),
    ]
