# Generated by Django 2.1.7 on 2019-12-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_auto_20191203_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simage',
            name='model',
            field=models.CharField(choices=[('1', 'Red Neuronal (Sin nubes)'), ('3', 'Naive Bayes (Multinomial)')], default='1', max_length=2),
        ),
    ]
