# Generated by Django 2.1.7 on 2020-06-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_auto_20191203_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='simage',
            name='platform',
            field=models.CharField(choices=[('0', 'LANDSAT_8')], default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='simage',
            name='product',
            field=models.CharField(choices=[('0', 'LS8_OLI_LARSRC')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='simage',
            name='model',
            field=models.CharField(choices=[('1', 'Red Neuronal (Sin nubes)'), ('3', 'Naive Bayes (Multinomial)'), ('4', 'Naive Bayes (Gausiano)')], default='1', max_length=2),
        ),
    ]
