# Generated by Django 2.1.7 on 2020-06-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_auto_20200624_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simage',
            name='source',
        ),
        migrations.RemoveField(
            model_name='simage',
            name='upload',
        ),
        migrations.AlterField(
            model_name='simage',
            name='model',
            field=models.CharField(choices=[('0', 'Neural Networks'), ('1', 'Support Vector Machine')], default='1', max_length=2),
        ),
    ]
