# Generated by Django 2.1.7 on 2020-06-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0009_auto_20200624_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simage',
            old_name='east',
            new_name='lat_max',
        ),
        migrations.RenameField(
            model_name='simage',
            old_name='north',
            new_name='lat_min',
        ),
        migrations.RenameField(
            model_name='simage',
            old_name='south',
            new_name='lon_max',
        ),
        migrations.RenameField(
            model_name='simage',
            old_name='west',
            new_name='lon_min',
        ),
        migrations.AddField(
            model_name='simage',
            name='date_max',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simage',
            name='date_min',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
