# Generated by Django 2.1.7 on 2020-06-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0010_auto_20200624_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simage',
            name='date_max',
            field=models.CharField(help_text='Date format AAAA-MM-DD. Example: 2016-01-01', max_length=20, verbose_name='Date Max'),
        ),
        migrations.AlterField(
            model_name='simage',
            name='date_min',
            field=models.CharField(help_text='Date format AAAA-MM-DD. Example: 2015-01-01', max_length=20, verbose_name='Date Min'),
        ),
        migrations.AlterField(
            model_name='simage',
            name='lat_max',
            field=models.CharField(help_text='Valid values 5.276905999999999 - 3.0384721000000003. Example: 3.9084', max_length=200, verbose_name='Latitude Max'),
        ),
        migrations.AlterField(
            model_name='simage',
            name='lat_min',
            field=models.CharField(help_text='Valid values 5.276905999999999 - 3.0384721000000003. Example: 3.6667', max_length=200, verbose_name='Latitude Min'),
        ),
        migrations.AlterField(
            model_name='simage',
            name='lon_max',
            field=models.CharField(help_text='Valid values -75.80698879999998,-74.491394. Example: -74.8039', max_length=200, verbose_name='Longitude Max'),
        ),
        migrations.AlterField(
            model_name='simage',
            name='lon_min',
            field=models.CharField(help_text='Valid values -75.80698879999998,-74.491394. Example: -75.0216', max_length=200, verbose_name='Longitude Min'),
        ),
        migrations.AlterField(
            model_name='simage',
            name='model',
            field=models.CharField(choices=[('0', 'Neural Networks'), ('1', 'Random Forest')], default='0', max_length=2),
        ),
    ]
